### ISSUE TITLE
Inconsistency: Permissions "menus"

### ISSUE THREAD

**Issue by stefanvd** [hober/web-extensions#188]
Currently, <code>menus</code> is supported in some browsers. And that only in the Firefox and Safari web browser (but not in iOS).
It lacks support in the following web browsers Google Chrome, Opera, Microsoft Edge.

```
browser.menus.create({
  id: "open-me",
  title: browser.i18n.getMessage("menuItemOpenPanel"),
  contexts: ["all"]
}, onCreated);
```

**Resources:**
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus
- https://blog.mozilla.org/addons/2017/08/10/webextensions-firefox-56/
- https://developer.apple.com/documentation/safariservices/safari_web_extensions/assessing_your_safari_web_extension_s_browser_compatibility
- https://groups.google.com/a/chromium.org/g/chromium-extensions/c/Wd04xaw01TA

**Comment by carlosjeurissen** [comment]
**Naming**
There seem to be two names for this API. `menus` and `contextMenus`. `menus` makes it multi-purpose so my proposal is to use `menus` going forward in Google Chrome as well.

**OS-menu bar**
The lack of context `tools_menu`. Which allows menu items to be added to the mac menu bar. Which can be considered adding to other browsers as well. This seems only supported in Firefox at the moment.

**Comment by Rob--W** [comment]
The two names are `menus` and `contextMenus`. There is no `menu`.

FYI on Firefox issue tracker there is also a mention of the two namespaces and potentially deprecating one: https://bugzilla.mozilla.org/show_bug.cgi?id=1718323

**Comment by Rob--W** [comment]
During today's meeting we talked about considering replacing contextMenus with "menus", and at the same time making a breaking change to the API to fix an API defect: let `menus.create` return a Promise instead of a string/integer.

The Firefox issue for that is at https://bugzilla.mozilla.org/show_bug.cgi?id=1527979.
I recall having chatted with Chromium engineers in person about this issue, but I cannot find a crbug right now.

@dotproto Can you comment here when you've heard back from your team about the interest in (1) replacing contextMenus with menus and (2) changing the API signature of `menus.create` / `contextMenus.create`?

**Comment by xeenon** [comment]
Safari already implements `menus` as an alias.

**Comment by Rob--W** [comment]
@xeenon To clarify, is this the behavior in Safari?

- menus permission = menus API only
- contextMenus permission = contextMenus API only

Firefox has the above behavior. The menus namespace also has more functionality than the contextMenus one, such as menus.getTargetElement, also available in content scripts: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/getTargetElement

I am asking because a potential interpretation of your comment is that requesting menus or contextMenus unlocks both namespaces.

**Comment by xeenon** [comment]
Yes, that is the behavior in Safari. We don't support the additional Firefox APIs.

**Comment by dotproto** [comment]
Chrome's current position is that the "menus" and "contextMenus" APIs and associated permissions provide two different sets of capabilities. Chrome does not currently support the concept of custom menus and does not intend to. We are concerned that merging these namespaces/permissions will lead to confusion regarding the intended scope of what Chrome supports.

**Comment by Rob--W** [comment]
Closing this ticket since it is unlikely for there to be any more discussion on this topic. The positions are clear:

- Firefox has implemented the `menus` API as a superset of the contextMenus API.
- Safari has implemented the `menus` API as an alias of the contextMenus API.
- Chrome is opposed to supporting the `menus` API/permission.
