### ISSUE TITLE
Background page service worker inspecting request Content-type misses first request when waking up

### ISSUE THREAD

**Issue by prushforth** [hober/web-extensions#246]
I believe this may be a [use case](https://github.com/w3c/webextensions/issues/72) that is not perfectly served by the current service worker approach.

We want to simulate the behaviour of browsers when they encounter a URL to an image, but for map documents.  They synthesize a page and insert a `<img src=_current_url_>` into the synthesized page.  The URL bar still contains the url to the image, but the image is rendered per a normal web page behaviour.

We want to listen to web requests, and inspect the Content-type header for "text/mapml". When that is found, we want to replace the content of the page with a synthesized html document that contains our custom element, and view the map.  The url bar will point to the original URL of the document, and the page will render (having the custom element embedded).

We've developed a M3 implementation of this that works well, except when the SW is waking up.  It misses the first page's headers. The sw goes to sleep very quickly, afaict about 30s or less.  So it looks like a heisenbug to the user, unless they know about the sw.

We don't want to have to keep the sw alive artificially, but that seems to be the only way to achieve better user behaviour.

**Comment by bershanskiy** [comment]
This does not sound like an intentional behavior, it sounds more like a race condition either in your extension or browser. Would you be able to link your extension (if it is public) so that I can take a closer look?

**Comment by prushforth** [comment]
It's not yet merged, but it's in a fork branch [here](https://github.com/ben-lu-uw/mapml-extension/tree/create_map_from_request).  If you take the trouble to test it, you'll need a URL to test it on,  here's [an example](https://geogratis.gc.ca/mapml/en/cbmtile/cbmt/?alt=xml) that should display as a map once you've got the extension running.

**Comment by bershanskiy** [comment]
You correctly identified that Chrome fails to wake up service worker and deliver the first webRequest event when service worker is shut down; looks like your colleague already [added a workaround](https://github.com/ben-lu-uw/mapml-extension/commit/bb774a98c8fad05239e0851d675ac7aa94f25593) which keeps background persistently active.

That workaround fixes the browser bug, but I see a few more issues with current implementation:
Current MapML detection logic has multiple async stages and does not store enough data (e.g., tab id) to ensure it actually runs on the same tab and makes lots of assumptions about timing of async operations. If I'm understanding correctly, background performs the following steps:
   1. background listens for `chrome.webRequest`, within handler `H1` calls `chrome.storage.local.get`;
   2. `H1-inner` handler receives response, sets `needToReload` to `true`;
   3. `H2` then receives `chrome.tabs.onUpdated` and _assumes_ it is the same tab, checks that `needToReload` is `true`, then sets `needToReload` to `false` and reloads the tab
   4. `H2-inner` sets `reloaded` to `true`;
   5. `H2` then receives another `chrome.tabs.onUpdated` and checks that `needToReload` is `false` and `reloaded` is `true` and moves on with injection which also happens in multiple stages...

This process is full of timing assumptions. For example, in step 1 and 2 `chrome.storage.local.get` might take a long while and simply return after the tab is fully loaded. In step 3, H2 assumes that (1) the tab did not finish loading before step 2 completed and (2) that no other tab finished loading between completion of step 2 and loading of the target tab. In step 5, `H2` once again assumes that it still sees the same tab and not another one.

In other words, if there is ever another tab being loaded/updated while detection logic is going on, detection logic is almost guaranteed to misinterpret something. At least, I would add a global variable tracking tab id initially observed by `chrome.webRequest` handler which all other handlers could check against. A better solution is to actually just simplify this whole detection logic.

### Proposal: Use content script

Make `sniffForMapML` the main detection mechanism and put it into a content script, remove `webRequest` and `tabs.onUpdated` handlers entirely. Effectively, detection logic can be just:
1. Inject `sniffForMapML` into every page (declaratively in manifest, in isolated world at document idle state)
2. If `sniffForMapML` detects MapML, it sends a message to background
3. background receives the message, extracts `sender.tabId`, stores it, registers netRequest/webRequest only for that tab id and content scripts and styles only for that tab id, then reloads the tab using that tab id.

This method is:
- more reliable because (1) it prevents any possibility of confusion because it uses a specific tab id and (2) it avoids any race conditions because in step 3 background can wait for all preparations to complete and only then reload the tab.
- can support multiple MapML tabs being loaded at once
- can easily support iframes, if you ever plan to add this functionality
- is more efficient because content scripts have almost no overhead (run in the same process as tab, etc.) while persistent/frequently invoked background has larger overhead
- is not susceptible to webRequest bug since message sent in point 2 will always wake up background

If you like, we can discuss my proposal and I can create a PR if you would be interested in reviewing it.

**Comment by prushforth** [comment]
> You correctly identified that Chrome fails to wake up service worker and deliver the first webRequest event when service worker is shut down; looks like your colleague already [added a workaround](https://github.com/ben-lu-uw/mapml-extension/commit/bb774a98c8fad05239e0851d675ac7aa94f25593) which keeps background persistently active.

Yes, the workaround does appear to yield more stable behavior.

> That workaround fixes the browser bug, but I see a few more issues with current implementation:

Thank you very much for taking time to review our solution. We will review your proposal in detail to see if we can follow that path. Certainly we are learning the ropes, and your suggestions are very much appreciated.

> If you like, we can discuss my proposal and I can create a PR if you would be interested in reviewing it.

That's kind of you and we would love to consider your contribution. We are working under the W3C community and business groups license, so if would you consider joining our CG for this purpose, it would make it more straightforward to consider.

**Comment by bershanskiy** [comment]
> Certainly we are learning the ropes, and your suggestions are very much appreciated.

Thanks! As a side note, I believe that the solution I proposed would also handle MapML tags embedded directly inside of other pages since `<mapml->`, `<map-head>`, `<map-body>` and all other MapML tags can be interpreted as custom HTML tags. In other words, one could include a MapML map inside their websites, blogs etc. as easily as including a `<video>` or other media, no need to open a dedicated page.

> if would you consider joining our CG for this purpose, it would make it more straightforward to consider.

Unfortunately, I'm not a member of W3C and joining for an individual is rather hard. May I just delegate any intellectual rights to W3C or someone else directly? At least in this case, it might take me less time implementing the solution I proposed than actually figuring out and coordinating all the legalese to join W3C.

**Comment by prushforth** [comment]
> Unfortunately, I'm not a member of W3C and joining for an individual is rather hard. 

You don't actually have to join the W3C!  Just the community group: https://www.w3.org/community/maps4html/join

> At least in this case, it might take me less time implementing the solution I proposed than actually figuring out and coordinating all the legalese to join W3C.

> May I just delegate any intellectual rights to W3C or someone else directly?

It's basically just creating an account, and it doesn't delegate any of your rights, it just says we can use your ideas in any future standard and you don't mind.

But I do understand if you can't join due to employer constraints and what have you.  We'll have a close look at your suggestions anyway and come back for advice if you don't mind?  Your help is very much appreciated!

> As a side note, I believe that the solution I proposed would also handle MapML tags embedded directly inside of other pages since <mapml->, <map-head>, <map-body> and all other MapML tags can be interpreted as custom HTML tags. In other words, one could include a MapML map inside their websites, blogs etc. as easily as including a <video> or other media, no need to open a dedicated page.

So this is already handled by the custom element itself. You can just use the `<mapml-viewer>` in any normal page and it works without the extension (of course the page author has to include the mapml-viewer.js module, but that isn't too much work.  An example of that is documented [here](https://maps4html.org/web-map-doc/docs/elements/mapml-viewer/).

Our custom element suite is not complete, in some future iteration we hope to custom-elementify the whole vocabulary (well, except the `<mapml->`, `<map-head>`, and `<map-body>` elements).

**Comment by prushforth** [comment]
@bershanskiy we applied your advice, and the [revised architecture ](https://github.com/ben-lu-uw/mapml-extension/tree/create_map_from_document) works well.

**Comment by bershanskiy** [comment]
It's great to to hear that this solution works well. Also, it is measurably more efficient than the old one, since it does not require listeners which would be waking up BG all the time. Please feel free to @ ping me directly if you need any help.

Unfortunately, I don't have a W3C account, but I'll try to set up one. Should I use this form? https://www.w3.org/accounts/request

I have just a few small nits (which I may be able to address myself after setting up W3C account):
 - in background script [line 38](https://github.com/ben-lu-uw/mapml-extension/blob/create_map_from_document/src/background.js#L38) refers to `request.command`, but `request` is never defined. It might be meant to be `message`. (But this code might be dead anyway, since as far as I know, nothing sends such messages right now.)
 - currently BG does not handle multiple MapML tabs being loaded at once. I'm not sure if this ever happens, but if it ever does it would be hard to debug.
 - currently BG uses `chrome.declarativeNetRequest.updateEnabledRulesets` to enable/disable ruleset for all tabs. It might be undesirable if there are multiple tabs being loaded at once, one of which does not contain a MapML element. It is _very_ unlikely even now, but can be entirely avoided by using `chrome.declarativeNetRequest.updateSessionRules` with a rule whose `condition` includes `tabIds` specifying current tab id.

**Comment by prushforth** [comment]
> Should I use this form? https://www.w3.org/accounts/request

It's been so long since I created mine, but I think you do need a W3C account before you can join the group, so yes.  If you are not successful, let me know and I will follow up.

> n background script [line 38](https://github.com/ben-lu-uw/mapml-extension/blob/create_map_from_document/src/background.js#L38) refers to request.command, but request is never defined. It might be meant to be message. (But this code might be dead anyway, since as far as I know, nothing sends such messages right now.)

Yes, it's dead, and we're cleaning it up in a next commit.

> currently BG does not handle multiple MapML tabs being loaded at once. I'm not sure if this ever happens, but if it ever does it would be hard to debug.

Yes, we did notice that and were wondering how to deal with scoping stored items to a tab.  Also, do we have to clean up local storage or it will blow up eventually if we store per-tab data and  if we don't clean up as tabs come and go; I imagine so.

> currently BG uses chrome.declarativeNetRequest.updateEnabledRulesets to enable/disable ruleset for all tabs. It might be undesirable if there are multiple tabs being loaded at once, one of which does not contain a MapML element. It is very unlikely even now, but can be entirely avoided by using chrome.declarativeNetRequest.updateSessionRules with a rule whose condition includes tabIds specifying current tab id.

That's a hot tip! We'll follow up.

Cheers

**Comment by bershanskiy** [comment]
@prushforth I joined the group, thanks for guidance. I believe the background does not really need to store any data into `chrome.storage` for reloading. I simplified logic a bit and created a PR: https://github.com/ben-lu-uw/mapml-extension/pull/3

> Yes, we did notice that and were wondering how to deal with scoping stored items to a tab.

As is, `chrome.storage.*` does not support scoping data to a tab, developers sometimes just include `tabId` in the storage key, as you/ben-lu-uw did.

> Also, do we have to clean up local storage or it will blow up eventually if we store per-tab data and if we don't clean up as tabs come and go; I imagine so.

[Extension currently has `unlimitedStorage` permission](https://github.com/Maps4HTML/mapml-extension/blob/main/src/manifest.json#L9), so in practice Chrome would allow you to store a lot of data without ever throwing errors. If extensions do not have `unlimitedStorage`, then `storage.local.set` will throw errors upon further writes if extension tries to store more than 5MB.

Edit: extension has `unlimitedStorage` permission.

**Comment by bershanskiy** [comment]
Summary for anyone stumbling into this issue:
 - this issue was an instance of [a more general issue where `webRequest` failed to wake up the service worker](https://bugs.chromium.org/p/chromium/issues/detail?id=1024211)
 - we worked around this issue by using content script which detects relevant element `<mapml->` and wakes up the background with a message
   - https://github.com/Maps4HTML/mapml-extension/blob/main/src/sniffForMapML.js
   - https://github.com/Maps4HTML/mapml-extension/pull/28

I'm not sure whether this still should stay open or can be closed now.

**Comment by prushforth** [comment]
If it's a known bug then as far as I'm concerned it can be closed.  It was raised as [a use case that isn't covered by service worker implementation of background scripts](https://github.com/w3c/webextensions/issues/72), but since it appears that it would be covered if the  bug didn't exist, let's close it.
