### ISSUE TITLE
Should dNR dynamic rules reset on update?

### ISSUE THREAD

**Issue by xeenon** [hober/web-extensions#251]
Chrome currently resets any dynamic dNR rules on extension update in the effort to force extensions to keep their static rules and dynamic rules in sync. Without this reset, any previously added dynamic rules might conflict with newly added static rules in the update.

Safari does not reset dynamic dNR rules on update and the extension could clear them and reapply any if needed.

I feel that a reset like in Chrome could potentially and surprisingly delete user generated content blocking rules that would require additional storage and management steps by the extension to preserve the rules and reapply them.

**Comment by hfiguiere** [comment]
The Google documentation [says](https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/#dynamic-and-session-scoped-rules):

> Rules added using the [updateDynamicRules](https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/#method-updateDynamicRules) API method are persisted across both sessions and extension updates.

So to me it looks like Chrome implementation doesn't follow it. And this is inconsistent.

Note on clearing the rules: this requires calling `getDynamicRules()` and then `updateDynamicRules()`. Shouldn't there be a (faster) "clear" function instead since this could slow down startup... (unless I really missed something)

**Comment by hanguokai** [comment]
Except `DynamicRules`,  there are other similar apis, like `registerContentScripts`, `alarms`, `contextMenus`... They create somethings dynamically when extension install/update or anytime when user want to change them. So what happen when browser start/quit, profile start/close, extension update and extension enable/disable? Does browser keep them automatically or clear them?

Because they are not clear, from a developer's point of view, I would clear and re-create them like below code, thus I don't have to care about how the browser handle them. There is a [discussion](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/ZM0Vzb_vuIs/m/VhBpDBIvAQAJ) for dynamic content script.
```
function onInstall(e) {
  // clear all dynamic content scripts, then re-register them.
  chrome.scripting.unregisterContentScripts(function() {
    chrome.scripting.registerContentScripts(one or more content scripts);
  });

  // clear all context menus, then re-create them.
  chrome.contextMenus.removeAll(function() {
    chrome.contextMenus.create(menu-1);
    chrome.contextMenus.create(menu-2);
    ……
  });

  // clear all alarms, then re-create them.
  chrome.alarms.clearAll(function() {
    chrome.alarms.create(name-1, config-1);
    chrome.alarms.create(name-2, config-2);
    ....
  });
  // if your alarm names are static, you can create them directly, no need to clear them first.
}

chrome.runtime.onInstalled.addListener(onInstall);
chrome.runtime.onStartup.addListener(onInstall);
```

Developers can save these dynamic created items in storage, so they can restore them when browser restart or extension update.

**Comment by bershanskiy** [comment]
> Because they are not clear, from a developer's point of view, I would clear and re-create them like below code, thus I don't have to care about how the browser handle them.

This is what I always do. Also, it is possible that during extension's lifespan, content script will be moved (path change), alarms renamed, contextMenu command names or button text updated, etc.. So registrations for older extension versions might not be relevant anymore and it is always conceptually easier/safer to just re-register them just in case.

**Comment by Rob--W** [comment]
> Chrome currently resets any dynamic dNR rules on extension update in the effort to force extensions to keep their static rules and dynamic rules in sync.

@dotproto While you did mention that dynamic rules are cleared, I tested the implementation and it looks like that is not the case. On the contrary, there is a bug in Chrome that prevents dynamic rules from being removed on uninstall (https://crbug.com/1302900).

When I trace the implementation, it looks like dynamic rules are intentionally kept, and only (intended/supposed to be) removed on uninstall. For example, here's internal documentation on the intended behavior of dynamic rule updates: https://source.chromium.org/chromium/chromium/src/+/main:extensions/browser/extension_prefs.cc;l=223-230;drc=7aa346a8ba6f861859a392d241ee8246303e94c6

**Comment by Rob--W** [comment]
Changing https://github.com/w3c/webextensions/labels/follow-up%3A%20chrome to https://github.com/w3c/webextensions/labels/opposed%3A%20chrome after discussing this with @rdcronin and @oliverdunk at TPAC 2023.

"opposed" in this group means "There is consensus that dynamic rules should not reset on update". In other words, that dynamic rules are persisted across extension updates.

Chrome will keep the current behavior (i.e. keeping dynamic rules on update). @oliverdunk will take care of ensuring that Chrome's documentation clarifies that dynamic rules are persistent.

I'll comment on the crbug to let the crbug owner know about this agreement, so that even if the crbug (https://crbug.com/1302900 - dynamic rules kept after uninstall) is fixed, that dynamic rules are still preserved across updates.
