### ISSUE TITLE
Should `browser.storage.local.set({"": ""})` and `browser.storage.local.get("")` be valid?

### ISSUE THREAD

**Issue by xeenon** [hober/web-extensions#278]
Currently Chrome supports doing `browser.storage.local.set({ "": "foo" })` and `browser.storage.local.get("")`. We always return an empty result object in Safari in if the key is empty. We have found an extension in the wild doing this, and will likely change Safari to match Chrome.

**Comment by bershanskiy** [comment]
For reference, Firefox also supports this (matches Chrome).

> We have found an extension in the wild doing this

This is interesting, is this extension public/in the store? Does it appear accidental or intentional?

**Comment by carlosjeurissen** [comment]
In any case, as we talked about in TPAC, for developers it would be very good to know about this behaviour in Safari even if it will be changed in the future. Mentioning it on this mdn page would be great: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageArea/set

Generally speaking an empty key is just valid in JSON, as can be seen in the standard:
https://www.ecma-international.org/publications-and-standards/standards/ecma-404/
"The JSON syntax does not impose any restrictions on
the strings used as names". And as can be seen in below figure, an empty key can be used without issue.

That plus the fact Google Chrome and Firefox already support this, it seems best to change the behaviour in Safari as well.

<img width="630" alt="string-ecma" src="https://user-images.githubusercontent.com/1038267/190861905-2effa7f6-bcdf-4e22-be47-f082be0c7fce.png">

**Comment by bershanskiy** [comment]
> Mentioning it on this mdn page would be great:

I decided to add this info to BCD and found the following curious detail:
```js
browser.storage.local.set({"":"example"})
browser.storage.local.get("", (a) => console.log(a[""]))
```
logs out `undefined`

However, 
```js
browser.storage.local.set({"":"example"})
browser.storage.local.get(null, (a) => console.log(a[""]))
```
logs out `example`

And
```js
browser.storage.local.set({"":"example"})
browser.storage.local.get([""], (a) => console.log(a[""]))
```
throws `Error: Invalid empty key found in array passed to storage.local.get()`

And
```js
browser.storage.local.remove("")
browser.storage.local.remove([""])
```
both throw `Error: Invalid empty key found in array passed to storage.local.remove()`

In other words, this is just a difference in querying code.

I'll add a note to MDN BCD.

Edit: I updated the examples a bit. Edit 2: added `remove()`

**Comment by carlosjeurissen** [comment]
@bershanskiy This was tested in Mozilla Firefox?

I have tested these cases in Google Chrome, and in Google Chrome they just return in all three cases like you would expect.

**Comment by bershanskiy** [comment]
> @bershanskiy This was tested in Mozilla Firefox?
> I have tested these cases in Google Chrome, and in Google Chrome they just return in all three cases like you would expect.

I tested those in Firefox (and, just for more confidence, on Chrome after replacing `browser` with `chrome`) and it works as expected in both.

I believe that Safari just has a bug in `browser.storage.local.get()` (while `browser.storage.local.set()` can save data with empty keys).

**Comment by xeenon** [comment]
Yes, `browser.storage.local.get()` is the broken part in Safari. We are working on fixing it. Thanks for adding a note to MDN!

**Comment by Rob--W** [comment]
> > @bershanskiy This was tested in Mozilla Firefox?
> > I have tested these cases in Google Chrome, and in Google Chrome they just return in all three cases like you would expect.
> 
> I tested those in Firefox (and, just for more confidence, on Chrome after replacing `browser` with `chrome`) and it works as expected in both.

Adding `implemented: firefox` because of this.

**Comment by carlosjeurissen** [comment]
Since we all agreed on the preferred behaviour, there seems to be no work left for this issue within the group. Should we close the issue in this case? Or do we want to keep it open until it has been implemented by Safari?

In any case, @xeenon can we add a note somewhere to update https://github.com/bershanskiy/browser-compat-data/blob/main/webextensions/api/storage.json under "empty_key", and change the "version_added" once this has been fixed by Safari?

**Comment by Rob--W** [comment]
> Since we all agreed on the preferred behaviour, there seems to be no work left for this issue within the group. Should we close the issue in this case? Or do we want to keep it open until it has been implemented by Safari?

IMO it's fine to close since we've completed the discussion on interoperability. But I'll leave it up to @xeenon to close this, in case having it open is helpful.

> In any case, @xeenon can we add a note somewhere to update https://github.com/bershanskiy/browser-compat-data/blob/main/webextensions/api/storage.json under "empty_key", and change the "version_added" once this has been fixed by Safari?

FYI the canonical repo is mdn/content, i.e. https://github.com/mdn/browser-compat-data/blob/main/webextensions/api/storage.json

I'm not sure if we need to list this in the BCD. This is an implementation bug for an uncommon scenario. I'm not opposed to documenting it, but I do wonder where we draw the line between an eventually obsolete historical note and an incompatibility that's worth calling out.

Technically, `partial_implementation` could be used, but that feels a bit too heavy for such an edge case. (https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#partial_implementation-requires-a-note)

**Comment by lapcat** [comment]
> For reference, Firefox also supports this (matches Chrome).
> 
> > We have found an extension in the wild doing this
> 
> This is interesting, is this extension public/in the store? Does it appear accidental or intentional?

I just stumbled upon this issue, and I suspect that it's referring to my own extension, considering that I filed a Feedback with Apple on the issue 6 weeks ago. The behavior is intentional. The keys represent site-specific options, and an empty key is used for the defaults.

I have a workaround for Safari that I don't need for Chrome or Firefox:

`const getKey = (website === "") ? null : website; // get "" returns an empty object!
  chrome.storage.local.get(getKey, function(result) {`

**Comment by lapcat** [comment]
I see in the [meeting notes](https://github.com/w3c/webextensions/blob/main/_minutes/2022-09-29-wecg.md#meeting-notes) that some people didn't like this behavior, but it's no different from standard JavaScript objects:

```
 > var testing = {"":"foo"};
 < undefined
 > testing;
 < {: "foo"}
 > testing[""];
 < "foo"
 > testing[""] = "bar";
 < "bar"
 > testing[""];
 < "bar"
```

**Comment by bershanskiy** [comment]
> I have a workaround for Safari that I don't need for Chrome or Firefox:
> 
> `const getKey = (website === "") ? null : website; // get "" returns an empty object! chrome.storage.local.get(getKey, function(result) {`

I actually created a [PR for MDN](https://github.com/mdn/content/pull/20931) to include this workaround. Not sure if it will be merged since this level of detail might be excessive for MDN.
