### ISSUE TITLE
Selecting OK on confirm() is not considered a user gesture for permissions 

### ISSUE THREAD

**Issue by tconfrey** [hober/web-extensions#736]
`if (confirm('BrainTool is not currently open. Click OK to open it now.')) {
                chrome.sidePanel.open({});
            }`
throws:
"Error: `sidePanel.open()` may only be called in response to a user gesture."

I'm guessing there might be an issue with the system dialogs running in a different context, but confirm() seems like one of the simplest and most obviously user-intended gestures.

**Comment by dotproto** [comment]
Does this issue present in other browsers?

**Comment by tconfrey** [comment]
It reproduces every time on Chrome, Edge and Brave. All at Chromium v131.

**Comment by patrickkettner** [comment]
I believe Simeon is asking if it is present in other browser engines. Since those are all on chromium, it would be expected for them to be behaving the same more or less.
If the behavior is consistent between browsers, then it would likely need to come from an upstream spec change. Extensions largely inherit what counts as user activation from the engine. So it would probably need to go up to the [UAPM section](https://html.spec.whatwg.org/multipage/interaction.html#user-activation-processing-model) of WHATWG for a decision on wether or not this is expected behavior.

**Comment by tconfrey** [comment]
Ah, ok, understood. Sorry but I can't help you there. My extension is
currently limited to Chromium based browsers, so I don't have a test
environment for anything else.

**Comment by patrickkettner** [comment]
@dotproto would you be able to check if it works in firefox? I know browser.identity.launchWebAuthFlow requires user interaction to launch, fwiw

**Comment by tophf** [comment]
The same behavior in the web platform as can be seen by copypasting this URL in the address bar `data:text/html,<body><script>confirm()&&document.body.requestFullscreen().then(()=>'OK',e=>''+e).then(m=>document.body.innerText=m)</script>`

**Comment by Rob--W** [comment]
As expressed in the meeting, this behavior is part of the web platform and not extension-specific.

Besides, the content of the dialog is not reliable. E.g. it would be surprising to users to activate a user gesture in this example:
`if (confirm("Do you want to stay on this page?")) { ... }`
