### ISSUE TITLE
Extensions menu keyboard shortcut

### ISSUE THREAD

**Issue by dotproto** [hober/web-extensions#8]
We've received a request to add a keyboard shortcut to invoke the extensions menu in Chrome ([crbug/1126331](https://bugs.chromium.org/p/chromium/issues/detail?id=1126331)). The requester suggested using <kbd>Alt</kbd>-<kbd>X</kbd> and @Rob--W suggested <kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>X</kbd> in an informal chat. 

I'm curious if any other browsers have a similar feature they might like to expose and if so whether it would make sense to align on a shortcut. At the moment I think we're leaning towards <kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>X</kbd> but we're open to feedback.

**Comment by Rob--W** [comment]
In choosing a shortcut, <kbd>Alt</kbd>-<kbd>something</kbd> (with and without shift) should not be used because it may conflict with the [`accesskey` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/accesskey) (in Chrome) and may conflict with menu items of the menu bar (in Firefox). This rules out the use of <kbd>Alt</kbd>-<kbd>X</kbd>.

It's for that reason that I proposed <kbd>Ctrl</kbd>-<kbd>Shift</kbd> over <kbd>Alt</kbd>. Note that although <kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>...</kbd> doesn't overlap with features on the web, it does may conflict with extension shortcuts: https://developer.chrome.com/extensions/commands#usage

<kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>X</kbd> is already assigned in Firefox, for toggling between RTL and LTR in input fields. So it is not likely going to be re-assigned to the extension menu, if we ever add one.

<kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>A</kbd> looks like a better choice to me. It is already used in Firefox, and triggering it currently opens `about:addons` in a new tab. Extensions who wish to be compatible with Chrome and Firefox should therefore not choose this shortcut in the `commands` API.

**Comment by dotproto** [comment]
Thanks for calling out that <kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>X</kbd> is already used in Firefox. I know you mentioned it before, but it slipped my mind while writing this up. You also called out potential conflict with extension shortcuts in that discussion. 

While it's obviously not ideal, IMO this conflict is not a dealbreaker given that the effect of the reassign shortcut will be immediately obvious to the end-user and the effect of opening the extension menu is still somewhat related to their intended action. That said, I will raise this with my team for further discussion.

**Comment by Rob--W** [comment]
Due to the formatting it may not be obvious, but I suggested a different shortcut (Ctrl-Shift-A) in my previous comment, instead of Ctrl-Shift-X. WDYT?

**Comment by dotproto** [comment]
Oh, shoot! I would have sworn I added a note about that in my last post, but obviously I didn't. Offhand <kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>A</kbd> sounds like a good option and I'll bring that back to the Chrome extensions team for consideration.

**Comment by jessieberlin** [comment]
Per discussion, can we move this to a different venue and close out this issue?

**Comment by Rob--W** [comment]
To clarify @jessieberlin's comment above: This issue tracker is about creating the Community Group where we will have public discussions about things that we would specify. During the discussion earlier today, we determined that the exact keyboard shortcuts themselves is not something that we would specify.
